export const SETTINGS_SCHEMA_VERSION = 2;

export function createDefaultSettings() {
  return {
    schemaVersion: SETTINGS_SCHEMA_VERSION,
    account: {
      emailMasked: '',
      phoneMasked: '',
      ageGroupStatus: 'unconfirmed',
      mfaEnabled: false,
      connectedDevices: [],
      accountHealth: 'ok',
      familyCenterConfigured: false,
    },
    privacy: {
      improveProduct: false,
      personalizeExperience: false,
      sponsoredActivityPersonalization: false,
      sponsoredThirdPartyPersonalization: false,
      allowVoiceInClips: true,
      fullProfileAudience: 'friends_and_servers',
      shareProfileUpdates: true,
      persistentVoiceVerificationCodes: false,
      dataRequestStatus: 'idle',
    },
    messaging: {
      sensitiveMediaFriends: 'blur',
      sensitiveMediaOthers: 'blur',
      sensitiveMediaServers: 'blur',
      ageRestrictedDmCommands: false,
      ageRestrictedIosServers: false,
      spamFilter: 'unknown_only',
      dmScope: 'all_servers',
      allowServerMemberDMs: true,
      filterUnknownServerDMs: true,
      friendRequestsEveryone: true,
      friendRequestsFriendsOfFriends: true,
      friendRequestsServerMembers: true,
      connectedGameDMs: true,
      gameDmDisplay: 'all',
      blockedUsers: [],
    },
    notifications: {
      desktopEnabled: true,
      taskbarFlash: true,
      notifySmallServerStreams: true,
      notifyFriendAnniversary: true,
      notifyFriendsOnline: true,
      notifyUpcomingServerEvent: true,
      reactionNotifications: 'all',
      soundNewMessage: true,
      soundCurrentChannelMessage: false,
      soundIncomingCall: true,
      disableAllNotificationSounds: false,
      unreadBadge: true,
      emailCommunication: true,
      emailSocial: true,
      emailProductUpdates: false,
      emailTips: false,
      emailRecommendations: false,
      emailMarketingUnsubscribed: false,
      aggregateWhenBusy: false,
    },
    voiceVideo: {
      streamPreviews: true,
      advancedStreamExpanded: false,
      soundEvents: {
        mute: true,
        unmute: true,
        deafen: true,
        undeafen: true,
      },
      moreSoundsExpanded: false,
      soundboardVolume: 100,
      entranceSoundServer: 'all',
      entranceSound: null,
      diagnosticsExpanded: false,
    },
    appearance: {
      themePreset: 'chronocord',
      customTheme: null,
      syncTheme: true,
      applyThemeToProfiles: false,
      serverThemeMode: 'server',
      appIcon: 'default',
      media: {
        linkedMedia: true,
        uploadedMedia: true,
        linkPreviews: true,
        emojiReactions: true,
        spoilers: 'click',
        splitThreads: true,
        showAvatars: true,
      },
      chatBox: {
        liveMarkdownPreview: true,
        emoticonsToEmoji: true,
        autocompleteStickers: false,
        autocompleteGames: true,
        showSendButton: false,
      },
      dmSearchScope: 'selected',
      streamer: {
        enabled: false,
        autoDetectStreamingApps: true,
        hidePersonalData: true,
        hideInviteLinks: true,
        disableSounds: true,
        disableNotifications: true,
        hideWindowFromCapture: false,
      },
    },
    accessibility: {
      chatFontSize: 16,
      underlineLinks: false,
      displayNameStyles: true,
      interfaceDensity: 'default',
      messageDensity: 'default',
      messageGroupSpacing: 16,
      zoom: 100,
      saturation: 100,
      saturationAffectsCustomColors: false,
      highContrast: false,
      syncContrastWithSystem: true,
      roleColorDisplay: 'names',
      officialMessageColor: 'none',
      reducedMotion: false,
      syncMotionWithSystem: true,
      foregroundGifs: true,
      animatedEmoji: true,
      stickerAnimation: 'always',
      ttsRate: 1,
      imageDescriptions: true,
      standardScreenReaderChatInput: false,
    },
    system: {
      showShortcutListBinding: ['CTRL', '/'],
      customShortcuts: [],
      assistantInstalled: false,
      assistantRunning: false,
      developerMode: false,
      appTestMode: false,
      appTestId: '',
      openOnStartup: false,
      startMinimized: false,
      minimizeToTray: true,
      hardwareAcceleration: true,
    },
    ui: {
      lastSettingsRoute: 'account.info',
      expandedGroups: {},
    },
  };
}
